# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LRDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(161, 429)
        self.lrRunButton = QtWidgets.QPushButton(Dialog)
        self.lrRunButton.setGeometry(QtCore.QRect(10, 380, 141, 31))
        self.lrRunButton.setObjectName("lrRunButton")
        self.svrKernelInput = QtWidgets.QLineEdit(Dialog)
        self.svrKernelInput.setGeometry(QtCore.QRect(80, 20, 71, 20))
        self.svrKernelInput.setText("")
        self.svrKernelInput.setMaxLength(5)
        self.svrKernelInput.setObjectName("svrKernelInput")
        self.svrKernelLabel = QtWidgets.QLabel(Dialog)
        self.svrKernelLabel.setGeometry(QtCore.QRect(40, 20, 71, 20))
        self.svrKernelLabel.setObjectName("svrKernelLabel")
        self.svrDegreeLabel = QtWidgets.QLabel(Dialog)
        self.svrDegreeLabel.setGeometry(QtCore.QRect(35, 50, 50, 20))
        self.svrDegreeLabel.setObjectName("svrDegreeLabel")
        self.svrDegreeInput = QtWidgets.QLineEdit(Dialog)
        self.svrDegreeInput.setGeometry(QtCore.QRect(80, 50, 71, 20))
        self.svrDegreeInput.setMaxLength(5)
        self.svrDegreeInput.setObjectName("svrDegreeInput")
        self.svrGammaLabel = QtWidgets.QLabel(Dialog)
        self.svrGammaLabel.setGeometry(QtCore.QRect(35, 80, 50, 20))
        self.svrGammaLabel.setMinimumSize(QtCore.QSize(50, 20))
        self.svrGammaLabel.setMaximumSize(QtCore.QSize(50, 20))
        self.svrGammaLabel.setObjectName("svrGammaLabel")
        self.svrGammaInput = QtWidgets.QLineEdit(Dialog)
        self.svrGammaInput.setGeometry(QtCore.QRect(80, 80, 71, 20))
        self.svrGammaInput.setMaxLength(5)
        self.svrGammaInput.setObjectName("svrGammaInput")
        self.svrCoefInput = QtWidgets.QLineEdit(Dialog)
        self.svrCoefInput.setGeometry(QtCore.QRect(80, 110, 71, 20))
        self.svrCoefInput.setToolTip("")
        self.svrCoefInput.setStatusTip("")
        self.svrCoefInput.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.svrCoefInput.setObjectName("svrCoefInput")
        self.svrCoefLabel = QtWidgets.QLabel(Dialog)
        self.svrCoefLabel.setGeometry(QtCore.QRect(42, 110, 50, 20))
        self.svrCoefLabel.setObjectName("svrCoefLabel")
        self.svrTolInput = QtWidgets.QLineEdit(Dialog)
        self.svrTolInput.setGeometry(QtCore.QRect(80, 140, 71, 20))
        self.svrTolInput.setToolTip("")
        self.svrTolInput.setStatusTip("")
        self.svrTolInput.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.svrTolInput.setObjectName("svrTolInput")
        self.svrTolLabel = QtWidgets.QLabel(Dialog)
        self.svrTolLabel.setGeometry(QtCore.QRect(57, 140, 50, 20))
        self.svrTolLabel.setObjectName("svrTolLabel")
        self.svrCLabel = QtWidgets.QLabel(Dialog)
        self.svrCLabel.setGeometry(QtCore.QRect(61, 170, 50, 20))
        self.svrCLabel.setObjectName("svrCLabel")
        self.svrShrinkLabel = QtWidgets.QLabel(Dialog)
        self.svrShrinkLabel.setGeometry(QtCore.QRect(26, 200, 50, 20))
        self.svrShrinkLabel.setObjectName("svrShrinkLabel")
        self.svrCacheLabel = QtWidgets.QLabel(Dialog)
        self.svrCacheLabel.setGeometry(QtCore.QRect(16, 230, 61, 20))
        self.svrCacheLabel.setObjectName("svrCacheLabel")
        self.svrVerbLabel = QtWidgets.QLabel(Dialog)
        self.svrVerbLabel.setGeometry(QtCore.QRect(29, 260, 50, 20))
        self.svrVerbLabel.setObjectName("svrVerbLabel")
        self.svrIterLabel = QtWidgets.QLabel(Dialog)
        self.svrIterLabel.setGeometry(QtCore.QRect(26, 290, 50, 20))
        self.svrIterLabel.setObjectName("svrIterLabel")
        self.svrCInput = QtWidgets.QLineEdit(Dialog)
        self.svrCInput.setGeometry(QtCore.QRect(80, 170, 71, 20))
        self.svrCInput.setToolTip("")
        self.svrCInput.setStatusTip("")
        self.svrCInput.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.svrCInput.setObjectName("svrCInput")
        self.svrShrinkInput = QtWidgets.QLineEdit(Dialog)
        self.svrShrinkInput.setGeometry(QtCore.QRect(80, 200, 71, 20))
        self.svrShrinkInput.setToolTip("")
        self.svrShrinkInput.setStatusTip("")
        self.svrShrinkInput.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.svrShrinkInput.setObjectName("svrShrinkInput")
        self.svrCacheInput = QtWidgets.QLineEdit(Dialog)
        self.svrCacheInput.setGeometry(QtCore.QRect(80, 230, 71, 20))
        self.svrCacheInput.setToolTip("")
        self.svrCacheInput.setStatusTip("")
        self.svrCacheInput.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.svrCacheInput.setObjectName("svrCacheInput")
        self.svrVerbInput = QtWidgets.QLineEdit(Dialog)
        self.svrVerbInput.setGeometry(QtCore.QRect(80, 260, 71, 20))
        self.svrVerbInput.setToolTip("")
        self.svrVerbInput.setStatusTip("")
        self.svrVerbInput.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.svrVerbInput.setObjectName("svrVerbInput")
        self.svrIterInput = QtWidgets.QLineEdit(Dialog)
        self.svrIterInput.setGeometry(QtCore.QRect(80, 290, 71, 20))
        self.svrIterInput.setToolTip("")
        self.svrIterInput.setStatusTip("")
        self.svrIterInput.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.svrIterInput.setObjectName("svrIterInput")
        self.svrDaysInput = QtWidgets.QLineEdit(Dialog)
        self.svrDaysInput.setGeometry(QtCore.QRect(80, 350, 71, 20))
        self.svrDaysInput.setToolTip("")
        self.svrDaysInput.setStatusTip("")
        self.svrDaysInput.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.svrDaysInput.setObjectName("svrDaysInput")
        self.svrDaysLabel = QtWidgets.QLabel(Dialog)
        self.svrDaysLabel.setGeometry(QtCore.QRect(40, 350, 50, 20))
        self.svrDaysLabel.setObjectName("svrDaysLabel")
        self.svrEpsInput = QtWidgets.QLineEdit(Dialog)
        self.svrEpsInput.setGeometry(QtCore.QRect(80, 320, 71, 20))
        self.svrEpsInput.setObjectName("svrEpsInput")
        self.svrEpsLabel = QtWidgets.QLabel(Dialog)
        self.svrEpsLabel.setGeometry(QtCore.QRect(35, 320, 40, 20))
        self.svrEpsLabel.setObjectName("svrEpsLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SVR"))
        self.lrRunButton.setText(_translate("Dialog", "Run"))
        self.svrKernelLabel.setText(_translate("Dialog", "kernel:"))
        self.svrDegreeLabel.setText(_translate("Dialog", "degree:"))
        self.svrGammaLabel.setText(_translate("Dialog", "gamma:"))
        self.svrCoefLabel.setText(_translate("Dialog", "coef0:"))
        self.svrTolLabel.setText(_translate("Dialog", "tol:"))
        self.svrCLabel.setText(_translate("Dialog", "C:"))
        self.svrShrinkLabel.setText(_translate("Dialog", "shrinking:"))
        self.svrCacheLabel.setText(_translate("Dialog", "cache_size:"))
        self.svrVerbLabel.setText(_translate("Dialog", "verbose:"))
        self.svrIterLabel.setText(_translate("Dialog", "max_iter:"))
        self.svrDaysLabel.setText(_translate("Dialog", "Days:"))
        self.svrEpsLabel.setText(_translate("Dialog", "epsilon:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

